# Generated by Django 5.1.6 on 2025-03-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
