# Generated by Django 5.1.6 on 2025-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_remove_userprofile_profile_picture'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, to='movies.movie'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
