# Generated by Django 5.2.1 on 2025-05-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_userprofile_is_private_alter_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
