# Generated by Django 5.1.7 on 2025-04-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='acting',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='cinematography',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
