# Generated by Django 5.1.7 on 2025-04-26 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_comment_acting_comment_cinematography_comment_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('movie', 'user')},
        ),
    ]
