# Generated by Django 5.2.1 on 2025-05-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='editet',
            field=models.BooleanField(default=False),
        ),
    ]
