# Generated by Django 5.2.1 on 2025-05-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_comment_editet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='editet',
            new_name='edited',
        ),
    ]
